FROM xaoc000/darknet4iofog

RUN python3 -c 'import cv2; print(cv2.__version__)'

RUN git clone https://github.com/Xaoc000/darknet.git

RUN pip3 install --upgrade pip

RUN mkdir /usr/local

ADD /usr/local/cuda-9.0 /usr/local/cuda-9.0/

RUN pip3 install iofog-python-sdk ws4py

WORKDIR darknet/darknet

RUN wget https://pjreddie.com/media/files/yolov3.weights

ENTRYPOINT ["bash", "start.sh"]